/** Command registrations, kept out of activate() so the wiring stays readable. */

import * as vscode from "vscode";
import { listModels } from "../core/ollama";
import type { ChatViewProvider } from "./chatViewProvider";
import { readConfig, setModel } from "./config";

export function registerCommands(
  context: vscode.ExtensionContext,
  provider: ChatViewProvider
): void {
  context.subscriptions.push(
    /**
     * A way in that does not depend on the activity-bar icon rendering at all.
     * `<viewId>.focus` is generated by VS Code for every contributed view.
     */
    vscode.commands.registerCommand("dconx.openChat", async () => {
      await vscode.commands.executeCommand("dconx.chat.focus");
    }),
    vscode.commands.registerCommand("dconx.newTask", () => provider.newTask()),
    vscode.commands.registerCommand("dconx.pickModel", () => pickModel(provider))
  );
}

async function pickModel(provider: ChatViewProvider): Promise<void> {
  const ollama = readConfig().ollama;

  let models: string[];
  try {
    models = await listModels(ollama);
  } catch (e) {
    void vscode.window.showErrorMessage((e as Error).message);
    return;
  }

  if (models.length === 0) {
    void vscode.window.showWarningMessage(
      `No models available at ${ollama.baseUrl}. Try: ollama pull qwen2.5-coder:7b`
    );
    return;
  }

  const picked = await vscode.window.showQuickPick(models, { placeHolder: "Ollama model" });
  if (!picked) return;

  await setModel(picked);
  provider.notifyModelChanged();
}
